### ISSUE TITLE
Broken with async/await under Babel 7.0.0-beta.0.

### ISSUE THREAD

**Issue by phyllisstein** [faceyspacey/babel-plugin-universal-import#14]
Hey there! Just noticed that the `universal-import` plugin chokes, a little cryptically, on async functions with the new Babel beta. Given this code:

```js
const importSans = async () => {
  try {
    require('vendor/fonts/din')

    if (!sessionStorage.getItem('sansLoaded')) {
      const FontFaceObserver = await import('fontfaceobserver/fontfaceobserver.standalone')
      const observer = new FontFaceObserver('PF DIN Text Pro', { weight: 400 })
      await observer.load()

      if (!__DEV__ && canStoreIn('sessionStorage')) sessionStorage.setItem('sansLoaded', true)
    }

    return true
  } catch (_) {
    return false
  }
}
```

...the transpiler spits out this message:

```
    ERROR in ./src/client.js
    Module build failed: Error: /Users/daniel/Repos/Ignota/rupertsberg/src/client.js: Unexpected return value from visitor method function newFn(path) {
              return fn.call(state, path, state);
            }
        at NodePath._call (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:71:13)
        at NodePath.call (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:42:17)
        at NodePath.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:99:12)
        at TraversalContext.visitQueue (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:137:18)
        at TraversalContext.visitSingle (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:96:19)
        at TraversalContext.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:178:19)
        at Function.traverse.node (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:108:17)
        at NodePath.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:110:19)
        at TraversalContext.visitQueue (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:137:18)
        at TraversalContext.visitSingle (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:96:19)
        at TraversalContext.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:178:19)
        at Function.traverse.node (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:108:17)
        at NodePath.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:110:19)
        at TraversalContext.visitQueue (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:137:18)
        at TraversalContext.visitSingle (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:96:19)
        at TraversalContext.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:178:19)
        at Function.traverse.node (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:108:17)
        at NodePath.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:110:19)
        at TraversalContext.visitQueue (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:137:18)
        at TraversalContext.visitMultiple (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:91:17)
        at TraversalContext.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:176:19)
        at Function.traverse.node (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:108:17)
     @ multi ./client
```

Removing the `async`/`await` clause unbroke the build, as did downgrading to Babel v6.

**Comment by phyllisstein** [comment]
Might be worth noting that switching back to `dual-import` also got the bundle building again.

**Comment by faceyspacey** [comment]
does universal-import have the issue with babel 6?

**Comment by phyllisstein** [comment]
Nope! Looks fine on v6---mostly just flagging something on the horizon, since I found a workaround that does the trick for now. 😬

**Comment by faceyspacey** [comment]
closing this as it's covered in #16
